Initial
gemini-testing/gemini-url-decorator pull request #1
Opened 2016-09-28 23:18 UTC by DudaGod

2016-09-29 15:25 UTC, tormozz48 requested changes

2016-09-29 15:25 UTC, tormozz48 commented on CONTRIBUTING.md
> +All bug fixes and new features should go to the [`master`](https://github.com/gemini-testing/hermione-url-decorator/tree/master) branch.
Копипаст.
hermione-url-decorator -> gemini-url-decorator

2016-09-29 15:25 UTC, tormozz48 commented on CONTRIBUTING.md
> +```
добавь bash

2016-09-29 15:25 UTC, tormozz48 commented on CONTRIBUTING.md
> +```
добавь bash

2016-09-29 15:25 UTC, tormozz48 commented on CONTRIBUTING.md
> +```
добавь bash

2016-09-29 15:25 UTC, tormozz48 commented on CONTRIBUTING.md
> +1. [Search](https://github.com/gemini-testing/hermione-url-decorator/issues) for same issues on github in order to prevent duplicates
gemini

2016-09-29 15:25 UTC, tormozz48 commented on README.md
> +
Почему пустой блок?

2016-09-29 15:25 UTC, tormozz48 commented on README.md
> +Suppose, you want to add query parameter `name` which is already present in your test url: `http://localhost/test/?name=bilbo` and you don't want to override it:
is already present**ed**

2016-09-29 15:25 UTC, tormozz48 commented on README.md
> +The result url will look like: `http://localhost/test/?name=bilbo&name=torin`. How you understand, the result will be the same if `concat` would be any value except `false`.
**As** you understand

2016-09-29 15:25 UTC, tormozz48 commented on README.md
> +Moreover for previous test url you can specify a set of values for one query parameter:
Also you can specify ...

2016-09-29 15:25 UTC, tormozz48 commented on README.md
> +If you want to override value of **name** query parameter:
`name`

2016-09-29 15:25 UTC, tormozz48 commented on README.md
> +If you want to override value of **name** query parameter:
В смысле не жирным а в бэктиках

2016-09-29 15:25 UTC, tormozz48 commented on README.md
> +As a result url will look like: `http://localhost/test/?name=torin`.
The result url will ...

2016-09-29 15:25 UTC, tormozz48 commented on lib/config.js
> +    return matched ? _.set({}, [matched[1], matched[2], 'value'], value) : {};
Я не понял: что это за ключ будет в объекте?

2016-09-29 15:25 UTC, tormozz48 commented on lib/config.js
> +    return matched ? _.set({}, [matched[1], matched[2], 'value'], value) : {};
`[matched[1], matched[2], 'value']`

2016-09-29 15:25 UTC, tormozz48 commented on lib/index.js
> +        return;
А мы не хотим здесь какой-то warning показывать?
Просто получается, что при этом условии плагин молча не будет ничего делать

2016-09-29 15:25 UTC, tormozz48 commented on package.json
> +    "gemini": "gemini-testing/gemini#fix/remove-facade",
Не забыть переключить версию gemini

2016-09-29 15:25 UTC, tormozz48 commented on test/lib/config.js
> +    it('should use concat value from config if environment variables have the same url parameter', () => {
should use `concated` или `concatenated`

2016-09-29 15:25 UTC, tormozz48 commented on package.json
> +    "sinon": "^1.17.5"
А где `sinon-chai` ???

2016-09-29 15:25 UTC, tormozz48 commented on test/lib/url-decorator.js
> +    it('should not add url parameters if they are specified as an empty object', () => {
Предлагаю вынести вот это `should not add url parameters` в describe, чтобы постоянно не повторять.

А тесты начинать:

* if they are specified as an empty object
* if they are specified as an object without "value" field

...

2016-09-29 15:25 UTC, tormozz48 commented on test/lib/url-decorator.js
> +    it('should concat each parameters from array of values', () => {
слово each лишнее

2016-09-29 15:25 UTC, tormozz48 commented on test/lib/url-decorator.js
> +    it('should concat parameters if "concat" is true', () => {
Опять же можно вынести `should concat parameters` в describe, а тесты называть:
* if "concat" is true
* if "concat" is not specified
* specified as number

2016-09-29 15:26 UTC, tormozz48 commented
Почему CI упал?

2016-09-29 18:34 UTC, DudaGod commented on README.md
> +
Он не пустой, в него входят Configuration и Examples.

2016-09-29 18:35 UTC, DudaGod commented on README.md
> +The result url will look like: `http://localhost/test/?name=bilbo&name=torin`. How you understand, the result will be the same if `concat` would be any value except `false`.
По моему по смыслу одно и тоже.

2016-09-29 18:37 UTC, DudaGod commented on README.md
> +Moreover for previous test url you can specify a set of values for one query parameter:
Мне тут нужно подчеркнуть, что ниже пример для того же самого урла и ниже указываю ожидаемый результат.

2016-09-29 18:38 UTC, DudaGod commented on README.md
> +As a result url will look like: `http://localhost/test/?name=torin`.
Мне мой вариант больше нравится =)

2016-09-29 18:41 UTC, DudaGod commented on lib/config.js
> +    return matched ? _.set({}, [matched[1], matched[2], 'value'], value) : {};
Вот так будет работать:

``` js
GEMINI_URL_QUERY_TEXT=name -> {query: {text: {value: 'name'}}}
```

И над функцией есть пример в jsdoc

2016-09-29 18:48 UTC, DudaGod commented on lib/index.js
> +        return;
В большей части плагинов которые я видел никакие варнинги при таких условиях не кидают. Поэтому в данном случае посчитал, что информации в README достаточно.

2016-09-29 18:48 UTC, DudaGod commented on package.json
> +    "gemini": "gemini-testing/gemini#fix/remove-facade",
уже оторвал

2016-09-29 18:49 UTC, DudaGod commented on package.json
> +    "sinon": "^1.17.5"
а зачем его ставить если все тесты написаны без его использования?

2016-09-29 18:51 UTC, DudaGod commented on test/lib/config.js
> +    it('should use concat value from config if environment variables have the same url parameter', () => {
should use `concat` value from config...
Бектики просто добавлю, это название поля у объекта

2016-09-29 19:01 UTC, DudaGod commented
спит он, сейчас разбужу =)

2016-09-30 10:55 UTC, tormozz48 commented on README.md
> +As a result url will look like: `http://localhost/test/?name=torin`.
У тебя выше написано `The result url will look like` - будь последователен

2016-09-30 10:55 UTC, tormozz48 commented on package.json
> +    "sinon": "^1.17.5"
ок

2016-10-03 14:17 UTC, DudaGod commented
/cc @sipayRT @tormozz48

2016-10-05 08:38 UTC, tormozz48 approved these changes

2016-10-05 08:38 UTC, tormozz48 commented on test/lib/config.js
> +    it('should redefine values from config by values from environment variables', () => {
redefine -> override или replace

2016-10-05 16:28 UTC, sipayRT requested changes
в остальном ок. Поправь и вливай

2016-10-05 16:28 UTC, sipayRT commented on README.md
> +```yaml
кажется, что тут нужно писать yml, т.к. ниже ломается подсветка. У меня пока только один варинат почему так происходит

2016-10-05 16:28 UTC, sipayRT commented on test/lib/url.js
> +        it('should return this for chaining', () => {
should be chainable

2016-10-05 16:28 UTC, sipayRT commented on test/lib/config.js
> +        it('should set "concat" field as true for query parameters if they are specified as a string', () => {
объедини этот тест с тестом ниже, т.к. они проверяют одно и то же - "should set "concat" field as true by default"

2016-10-05 16:28 UTC, sipayRT commented on test/lib/url-decorator.js
> +        assert.isUndefined(suite.url);
```js
assert.doesNotChange(() => decorateUrl({suite}), suite, 'url');
```

2016-10-05 16:28 UTC, sipayRT commented on test/lib/url-decorator.js
> +    it('should add new parameters if they do not exist in url', () => {
do --> does

2016-10-05 16:28 UTC, sipayRT commented on test/lib/url-decorator.js
> +        it('if "concat" is not specified', () => {
замени текст на "by default" и сделай его первым

2016-10-05 20:53 UTC, DudaGod commented on test/lib/url-decorator.js
> +    it('should add new parameters if they do not exist in url', () => {
Нет, здесь должно быть do.
does было бы в таком случае -> '...if **it** does not exist...'

2016-10-05 20:58 UTC, DudaGod commented on README.md
> +```yaml
поменял, результат такой же...

2016-10-05 21:03 UTC, merged